server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    rule: random
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: parking-service
          uri: lb://parking-service
          predicates:
            - Path=/api/parking/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

